project:
  type: website
  output-dir: docs

website:
  title: "PSYC 640 - Grad Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lecture_slides.qmd
        text: "Lecture Slides"
      - href: lecture_code.qmd
        text: "Lecture Code"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

