project:
  type: website
  output-dir: docs

website:
  title: "PSYC 640 - Grad Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Lectures"
        menu: 
          - text: "Week 5 - Pre-Lab"
            href: "lectures/05_Pre-Lab-speaker.html"
          - text: "Week 5 - Hypotheses & Power"
            href: "lectures/05_Hypothesis-Power-speaker"
          - text: "Week 6 - Categorical Data"
            href: "lectures/06_OneSample-speaker.html"
      - href: lecture_code.qmd
        text: "Lecture Code"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

