project:
  type: website
  output-dir: docs

website:
  title: "PSYC 640 - Grad Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Lectures"
        menu: 
          - text: "Week 5 - Pre-Lab"
            href: "lectures/05_Pre-Lab.html"
          - text: "Week 5 - Hypotheses & Power"
            href: "lectures/05_Hypothesis-Power"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

