project:
  type: website
  output-dir: docs

website:
  title: "PSYC 640 - Grad Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lecture_slides.qmd
        text: "Lecture Slides"
      - href: lecture_code.qmd
        text: "Lecture Code"
        
  right:
    - text: Previous Years
      menu:
      - text: 2023
        href: "https://dharaden.github.io/psyc640_2023"
    - icon: fa-github
      href: https://dharaden.github.io/psyc640
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

